repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
        args:
          - --pattern=main
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.2
    hooks:
        - id: commitizen
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
    -   id: markdown-toc
        # optional custom config:
        args: [--indent, "  ", -i]
    -   id: dockerfile_lint
        # optional custom config:
        args: [--json, --verbose, --dockerfile]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
      - id: insert-license
        files: \.groovy$
        args:
          - --license-filepath
          - LICENSE       # defaults to: LICENSE.txt
          - --comment-style
          - //                            # defaults to:  #
